### ISSUE TITLE
Fix: Date field in mediaviewer needs to be more specific

### ISSUE THREAD

**Issue by roar-larsen** [equinor/dm-core-packages#1029]
What is the date field here supposed to indicate? Is it the upload date? The date the photo/video/document was created? The date the file was last modified? The field needs to be more specific what the date is telling the user. Consider the need for more date fields.

![Image](https://github.com/equinor/dm-core-packages/assets/38418577/2b7fd666-4836-41f2-a84e-606a2aaac019)

**Comment by henrikbossart** [comment]
No date is provided with the file, so the date field will be removed.
