### ISSUE TITLE
Plugin for showing list of objects/primitives

### ISSUE THREAD

**Issue by soofstad** [equinor/dm-core-packages#104]
- [x] https://github.com/equinor/data-modelling-storage-service/issues/359
- [x] https://github.com/equinor/dm-core-packages/issues/109
- [ ] https://github.com/equinor/dm-core-packages/issues/151 override in parent what UI plugin to use for children (child) (this will be added to tabs and sidebar plugin). (This is a part of the grid now and need to be added for attribute-selector, other issues exist for this)

**Comment by eoaksnes** [comment]
(keep for history)

Option 
1. Mark uiRecipes as "array plugin" 
2. Config in parent blueprint/recipe
3. Extra middleman blueprint (etc. "AssetList")

**Comment by l3abak** [comment]
- The concept of "View" will fix the issue of selecting and modifying the ui recipe from the parent. 
- All attributes in the form of array to be treated as complex attributes. 
- - For the Tabs plugin, this means opening them in a new tab. with possibility
-
