### ISSUE TITLE
feat(form): add hyperlink widget

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-core-packages#1096]
A form widget for hyper links would be very useful. Let's do similar to DimentionalScalar widget

- [x] Create a hyperlink widget in Form with config.
- [x] could be applied on a string attribute and treat it as a hyperlink.
- [x] Config provide the possibility to define "label" to be shown instead of hyper link.
- [x] Widget use a special icon, 
- [x] Add a URL Blueprint to system/SIMOS extending "CORE:Entity" with attributes, value:string to be exclusively used for URLs.
- [x] Make an example with this url entity being used with the hyperlink widget. 

Deleted?
❌ Config provide the possibility to overwrite the icon (not important)

**Comment by soofstad** [comment]
Perhaps we can use dimensional scalar for this
