### ISSUE TITLE
refactor: create/move tabs ui recipes selector as plugin

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-core-packages#111]
Instead of begin hardcoded inside dm-core, make it as a plugin.

**Comment by l3abak** [comment]
I think we need to just merge ui-recipe selector and attribute-selector into one generic selector using "View" concept as implemented in Grid plugin.

**Comment by eoaksnes** [comment]
If it's hard to merge, maybe just share code inside the dm-core-packages, but keep as two plugins.

**Comment by KristianKjerstad** [comment]
instead of mering RecipeSelector with attribute-selector.

Can we merge RecipeSelector (see screenshot above) with the UiRecipesSideBarSelector?


![Image](https://user-images.githubusercontent.com/69512295/235677323-336c8d22-e122-4559-9f2d-77813479d240.png)

**Comment by soofstad** [comment]
I think we should scratch both of these "plugins".
The same can be achieved with "AttributeSelector" with scope "self".

**Comment by l3abak** [comment]
Yes, that is what I meant with “ one generic plugin based in view concept “. Attribute selector, which can show things in tabs or side bar cal achieve that. But you still need the tab/sidebar plugin to create a “view”. The rest of the logic can be achieved with good default behaviour.
