### ISSUE TITLE
UI(show-logs-dialog): too many scroll bars and close button

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#1111]
need to have scrolling only on the content, and not on the whole dialog. 
Should wrap content horisonally instead of scroll horisontal. 
Perhaps also remove the close button because you can just click away.

**Comment by collinlokken** [comment]
Could you provide some screenshot of what you are referring to @pbullhove ?

**Comment by pbullhove** [comment]
Ye! 

So you have to scroll horisontally in order to see everything, which makes it hard to see. 

Also, in an example that babak had, (was not able to reproduce now), then the whole dialog had a scroll bar, not only the content. So that there was a scrollbar on the content, and a scroll bar on the content+buttons. Which meant there were two scroll bars. Don't know if this is very recently fixed? 

![Image](https://github.com/equinor/dm-core-packages/assets/37016135/8f5a2bbd-ce89-4d05-b24e-56f3b0559bd3)
