### ISSUE TITLE
fix: datagrid minor bugs

### ISSUE THREAD

**Issue by awesthouse** [equinor/dm-core-packages#1147]
- [x] Optional DataGrid disappears after removing the last value in form
- [x] No support for creating arrays based on dimensions if attribute was optional and undefined in form
- [x] Table by default uses too much width
- [x] Formatting "-" as a number when trying to write negative numbers creates a NaN error
- [x] Add Undo/redo button
- [x] Pagination ignores printDirection (should maybe work now with updated way of using printDirection(?))

**Comment by l3abak** [comment]
The width problem is solved in the current release. No need to do more there. 
![image](https://github.com/equinor/dm-core-packages/assets/42837660/f3704393-1b81-4c28-bffa-b6ff5a985c89)
