### ISSUE TITLE
fix: scrolling issue with datepicker view

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#1189]
So can't see it ... 
Probably because it's a dialog, and it overlays instead of taking up the space itself. 

![Image](https://github.com/equinor/dm-core-packages/assets/37016135/d9f56ca5-5372-4972-8317-567732aefadb)

**Comment by collinlokken** [comment]
Unable to replicate

**Comment by collinlokken** [comment]
Think it was fixed in the new scrolling update 😄

**Comment by pbullhove** [comment]
@collinlokken 

Don't think so. I fixed it in SIMPOS by setting heigh: 100vh on the whole component. 

But you can try to reproduce it with a "small" component that gets a Popover. 
Or reproduce it by removing the 100vh line from PlatformSignalsOmnia.tsx

I guess the height of the component does not increase when the popover comes up, and therefore you can't scroll any higher than that.
