### ISSUE TITLE
feat: add to sidebar support to specify attributes

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#119]
right now the Sidebar component inside AttributeSelector plugin will display all of the entity's attributes in the sidebar. 

Update the ui recipe config such that it can take a list of string that specify what attributes to display in the sidebar.

**Comment by eoaksnes** [comment]
@soofstad update how to test it

**Comment by eoaksnes** [comment]
"visibleAttributes": ["firstAttribute", "thirdAttribute"]
