### ISSUE TITLE
fix: table is changing size when enabling/disabling edit mode

### ISSUE THREAD

**Issue by roar-larsen** [equinor/dm-core-packages#1236]
Parts of table plugin becomes squeezed when entering edit mode. 

![Image](https://github.com/equinor/dm-core-packages/assets/38418577/93817e68-6d62-46ca-8bcf-4e9ea3f56677)

![Image](https://github.com/equinor/dm-core-packages/assets/38418577/1e813609-de13-484c-8f1f-3bd8e806a3cf)

![Image](https://github.com/equinor/dm-core-packages/assets/38418577/2b6d5d03-bfc2-4c6d-b4fd-9f510e769965)

**Comment by awesthouse** [comment]
Pretty sure this is fixed by both the PR setting table width to 100% and pagination is fixed in #1269
