### ISSUE TITLE
fix: values in table is not updating correctly

### ISSUE THREAD

**Issue by roar-larsen** [equinor/dm-core-packages#1239]
When updating values through "open in tab" option, then the saved values are not updated in the table without refreshing the page.

Also, if you edit a cell/row (in any mode), but do not save, you have to refresh to get the original values back. Could this be handled more smoothly?

![Image](https://github.com/equinor/dm-core-packages/assets/38418577/e68660d0-a6c6-41c0-bdb3-062a64a9f126)

**Comment by awesthouse** [comment]
Will be fixed with #1222

**Comment by awesthouse** [comment]
Part of improve performance task
On branch: https://github.com/equinor/dm-core-packages/tree/feature/entity-context
