### ISSUE TITLE
bug: SIMPOS header does not span whole application width

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#1257]

**Comment by collinlokken** [comment]
![Image](https://github.com/equinor/dm-core-packages/assets/43639886/bffb7856-26c2-4b52-94e4-4be20565d67c)
This div needs 100% width



![Image](https://github.com/equinor/dm-core-packages/assets/43639886/a581d1ce-9e92-40b1-b1e7-24eb92138fe9)
