### ISSUE TITLE
datagrid: implement delete all button

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#1363]
A trash can on the side of the gear 
- [x] make the trash can
- [x] make clicking it delete the table
- [x] fix remove last row + submit bug. 
- [x] also make the width of the empty data grid be full width

- [x] small fix: add another ] to the [deg] that is missing one square parenthesis

**Comment by eoaksnes** [comment]
test: does this work on list that has fixed dimensions?
