### ISSUE TITLE
refactor: remove loading and eds-dependencies from dm-core components

### ISSUE THREAD

**Issue by awesthouse** [equinor/dm-core-packages#1365]
**Why**
We want dm-core to be free of all styling and dependencies to EDS.
We want loading to be mostly handled by plugin, and for the most part, getting the uiRecipe, attribute and calling ViewCreator/EntityView is too quick for the loading state to have any effect other than "blinking" 

**Task**
- [ ] Remove loading UI in EntityView and ViewCreator
- [ ] Try to remove dependencies to EDS in dm-core components

**Comment by soofstad** [comment]
done
