### ISSUE TITLE
Tabs plugin with form does not work with array of non-contained elements

### ISSUE THREAD

**Issue by l3abak** [equinor/dm-core-packages#139]
#### Expected Behaviour
Should work with array of non-contained elements. 
#### Actual Behaviour

my-app-cli1-dmss-1       | INFO:2023-03-10 14:00:57,049 Updated document '4483c9b0-d505-46c9-a157-94c79f4d7a6a.studyNC.cases''
my-app-cli1-dmss-1       | DEBUG:2023-03-10 14:00:57,050 PUT /api/documents/AppStorage/4483c9b0-d505-46c9-a157-94c79f4d7a6a.studyNC.cases - 5ms - 200
my-app-cli1-dmss-1       | INFO:     172.18.0.1:33336 - "PUT /api/documents/AppStorage/4483c9b0-d505-46c9-a157-94c79f4d7a6a.studyNC.cases?update_uncontained=false HTTP/1.1" 200 OK
my-app-cli1-dmss-1       | DEBUG:2023-03-10 14:01:01,376 GET /api/blueprint/dmss://AppStorage/models/signals_simple/Case - 1ms - 200
my-app-cli1-dmss-1       | INFO:     172.18.0.1:33336 - "GET /api/blueprint/dmss%3A//AppStorage/models/signals_simple/Case?context=signalApp HTTP/1.1" 200 OK
my-app-cli1-dmss-1       | DEBUG:2023-03-10 14:01:01,383 GET /api/blueprint/dmss://AppStorage/models/signals_simple/Case - 1ms - 200
my-app-cli1-dmss-1       | INFO:     172.18.0.1:33336 - "GET /api/blueprint/dmss%3A//AppStorage/models/signals_simple/Case?context=signalApp HTTP/1.1" 200 OK
my-app-cli1-dmss-1       | Traceback (most recent call last):
my-app-cli1-dmss-1       |   File "/code/src/features/document/use_cases/get_document_use_case.py", line 14, in get_nested_dict_attribute
my-app-cli1-dmss-1       |     return entity[path_list[0]]  # type: ignore
my-app-cli1-dmss-1       |            ~~~~~~^^^^^^^^^^^^^^
my-app-cli1-dmss-1       | IndexError: list index out of range
my-app-cli1-dmss-1       | 
my-app-cli1-dmss-1       | During handling of the above exception, another exception occurred:
my-app-cli1-dmss-1       | 
my-app-cli1-dmss-1       | Traceback (most recent call last):
my-app-cli1-dmss-1       |   File "/code/src/features/document/use_cases/get_document_use_case.py", line 15, in get_nested_dict_attribute
my-app-cli1-dmss-1       |     return get_nested_dict_attribute(entity[path_list[0]], path_list[1:])  # type: ignore
my-app-cli1-dmss-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
my-app-cli1-dmss-1       |   File "/code/src/features/document/use_cases/get_document_use_case.py", line 17, in get_nested_dict_attribute
my-app-cli1-dmss-1       |     raise KeyError(f"Attribute/Item '{path_list[0]}' does not exists in '{entity}'")
my-app-cli1-dmss-1       | KeyError: "Attribute/Item '0' does not exists in '[]'"
my-app-cli1-dmss-1       | 
my-app-cli1-dmss-1       | During handling of the above exception, another exception occurred:
my-app-cli1-dmss-1       | 
my-app-cli1-dmss-1       | Traceback (most recent call last):
my-app-cli1-dmss-1       |   File "/code/src/features/document/use_cases/get_document_use_case.py", line 15, in get_nested_dict_attribute
my-app-cli1-dmss-1       |     return get_nested_dict_attribute(entity[path_list[0]], path_list[1:])  # type: ignore
my-app-cli1-dmss-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
my-app-cli1-dmss-1       |   File "/code/src/features/document/use_cases/get_document_use_case.py", line 17, in get_nested_dict_attribute
my-app-cli1-dmss-1       |     raise KeyError(f"Attribute/Item '{path_list[0]}' does not exists in '{entity}'")
my-app-cli1-dmss-1       | KeyError: "Attribute/Item 'cases' does not exists in '{'type': 'dmss://AppStorage/models/signals_simple/StudyNC', 'cases': []}'"
my-app-cli1-dmss-1       | 
my-app-cli1-dmss-1       | During handling of the above exception, another exception occurred:
my-app-cli1-dmss-1       | 
my-app-cli1-dmss-1       | Traceback (most recent call last):
my-app-cli1-dmss-1       |   File "/code/src/common/responses.py", line 57, in wrapper_decorator
my-app-cli1-dmss-1       |     result = func(*args, **kwargs)
my-app-cli1-dmss-1       |              ^^^^^^^^^^^^^^^^^^^^^
my-app-cli1-dmss-1       |   File "/code/src/features/document/document_feature.py", line 37, in get_by_id
my-app-cli1-dmss-1       |     return get_document_use_case(
my-app-cli1-dmss-1       |            ^^^^^^^^^^^^^^^^^^^^^^
my-app-cli1-dmss-1       |   File "/code/src/features/document/use_cases/get_document_use_case.py", line 37, in get_document_use_case
my-app-cli1-dmss-1       |     document = get_nested_dict_attribute(document, attribute.split("."))
my-app-cli1-dmss-1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
my-app-cli1-dmss-1       |   File "/code/src/features/document/use_cases/get_document_use_case.py", line 17, in get_nested_dict_attribute
my-app-cli1-dmss-1       |     raise KeyError(f"Attribute/Item '{path_list[0]}' does not exists in '{entity}'")
my-app-cli1-dmss-1       | KeyError: "Attribute/Item 'studyNC' does not exists in '{'_id': '4483c9b0-d505-46c9-a157-94c79f4d7a6a', 'type': 'dmss://AppStorage/models/SignalApp', 'name': 'signalApp', 'description': 'This is an app for generating and plotting sin signals.', 'label': '', 'dataSources': ['AppStorage'], 'study': {'type': 'dmss://AppStorage/models/signals_simple/Study', 'cases': [{'type': 'dmss://AppStorage/models/signals_simple/Case', 'name': '', 'duration': 0, 'timeStep': 0, 'components': [], 'signal': {'type': 'dmss://AppStorage/models/containers/EquallySpacedSignal', 'name': 'signal', 'description': 'signal desc', 'value': [2, 4, 5, 67, 23, 4, 6, 4, 100, 100, 100], 'xname': '', 'xdescription': '', 'xunit': 's', 'xdelta': 1, 'xstart': 0, 'xlabel': 'time', 'label': ' ', 'legend': ' ', 'unit': 'm'}}]}, 'studyNC': {'type': 'dmss://AppStorage/models/signals_simple/StudyNC', 'cases': []}}'"
my-app-cli1-dmss-1       | ERROR:2023-03-10 14:01:01,393 Unexpected unhandled exception: "Attribute/Item 'studyNC' does not exists in '{'_id': '4483c9b0-d505-46c9-a157-94c79f4d7a6a', 'type': 'dmss://AppStorage/models/SignalApp', 'name': 'signalApp', 'description': 'This is an app for generating and plotting sin signals.', 'label': '', 'dataSources': ['AppStorage'], 'study': {'type': 'dmss://AppStorage/models/signals_simple/Study', 'cases': [{'type': 'dmss://AppStorage/models/signals_simple/Case', 'name': '', 'duration': 0, 'timeStep': 0, 'components': [], 'signal': {'type': 'dmss://AppStorage/models/containers/EquallySpacedSignal', 'name': 'signal', 'description': 'signal desc', 'value': [2, 4, 5, 67, 23, 4, 6, 4, 100, 100, 100], 'xname': '', 'xdescription': '', 'xunit': 's', 'xdelta': 1, 'xstart': 0, 'xlabel': 'time', 'label': ' ', 'legend': ' ', 'unit': 'm'}}]}, 'studyNC': {'type': 'dmss://AppStorage/models/signals_simple/StudyNC', 'cases': []}}'"
my-app-cli1-dmss-1       | DEBUG:2023-03-10 14:01:01,394 GET /api/documents/AppStorage/4483c9b0-d505-46c9-a157-94c79f4d7a6a.studyNC.cases.0 - 4ms - 500
my-app-cli1-dmss-1       | INFO:     172.18.0.1:33336 - "GET /api/documents/AppStorage/4483c9b0-d505-46c9-a157-94c79f4d7a6a.studyNC.cases.0?depth=1 HTTP/1.1" 500 Internal Server Error
#### Steps to Reproduce

**Comment by eoaksnes** [comment]
@l3abak please try again to reproduce this and make a step-by-step re-create for us to test.
