### ISSUE TITLE
fix: partial update not working as expected (?)

### ISSUE THREAD

**Issue by awesthouse** [equinor/dm-core-packages#1416]
**Branch**
https://github.com/equinor/dm-core-packages/tree/fix/form-payload

**Entrypoint**
SIMPOS -> "Analyses"-> "Positioning" -> "Line Tensions" -> pick a run

### Expected behavior
When only updating and passing some primitives, it should update the passed new values and keep old values for primitives not in payload.

**Test form - Scenario form with fields label and description**
![Skjermbilde 2024-03-22 kl  12 26 32](https://github.com/equinor/dm-core-packages/assets/25383299/822b1a04-b546-4617-8643-1ef149f4f268)

**Blueprint**
https://github.com/equinor/dm-app-simpos/blob/main/application/app/data/SIMPOSDS/mtsmo/analysis/positioning/srs/Scenario.json

**Example Payload**
```json
{ "type": "dmss://SIMPOSDS/mtsmo/analysis/positioning/srs/Task", "label": "Offset ULS UPDATED" }
```

### What happens
It updates label value, but removes other primitive values from object, like description. Seems to keep complex objects.

## Throws error on missing required primitive in complex object
Think this is actually related to the issue above where it doesn't keep the unchanged primitive values. If you try updating one field in Wave form, it will throw an error saying that the other unsent fields are required and missing, and if you edit all fields in Wave form, it throws an error saying "Missing required attribute 'seed'" which is a required attribute in Wave, but not shown in the UI. If you try submitting a form with all optional values (like Analyses -> Stability) it saves without error, but doesn't keep unchanged/previous values.

**Comment by soofstad** [comment]
@awesthouse not able to recreate this. Everything seems to work okey on the tests I've been doing.
Can you show the whole request going to DMSS?
Or, we can have a sit down together on this
