### ISSUE TITLE
Feature (views): Add concept of views to attribute-selector and recipe-selector

### ISSUE THREAD

**Issue by l3abak** [equinor/dm-core-packages#151]
#### Suggest Solution
The same is Grid plugin, the concept of selecting a plugin for based on different recipes and for different attributes could be solved using the "View" concept. 

Adding that would merge the two plugins and create a "Selector" plugin which would be much easier to use and maintain. 

#### Additional Details
- [x] recipe-selector
- [ ] attribute-selector

**Comment by eoaksnes** [comment]
Add icon after merging the plugins.
