### ISSUE TITLE
feature(grid): add option for frame and icons for grid

### ISSUE THREAD

**Issue by l3abak** [equinor/dm-core-packages#152]
#### Suggest Solution
Grid plugin could have an option for adding a frame with icons, title, and resize possibility. 

"Selector" plugin could use the option for adding customized icons and labels to entries of each view. 

The could simply be added to the "View" Blueprint for consumption of the plugin. 
#### Additional Details

**Comment by KristianKjerstad** [comment]
From the text description alone its difficult to understand what the final design should look like. 

We need a design session and sketches  before we can start on this

**Comment by eoaksnes** [comment]
duplicate
