### ISSUE TITLE
feat(dm-core, dm-core-plugins): call back function to tie plugins together for submitting and updating

### ISSUE THREAD

**Issue by l3abak** [equinor/dm-core-packages#153]
#### Suggest Solution

- controllable updating of ui-plugins is needed 
- recursive submitting of data to tie different ui-plugins together is needed. 

#### Additional Details

**Comment by l3abak** [comment]
Interesting, where do you plan to use this?

**Comment by KristianKjerstad** [comment]
(Some time ago, we decided to implement and test this functionality individually, before having a new meeting to discuss and compare solutions).

**Comment by ingeridhellen** [comment]
What about using the [observer pattern](https://www.patterns.dev/posts/observer-pattern)?

**Comment by eoaksnes** [comment]
https://tanstack.com/query/v3/docs/react/overview
