### ISSUE TITLE
feat: improve structure of example demo in dm-core-packages to describe different test cases

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#188]
- [x] update /app/... folder structure to make it easy to show what the different test cases are
- [x] just use the tree to select between the different test cases
- [x] remove everything except the tree from the frontend

**Comment by eoaksnes** [comment]
Maybe the structure can be:

```
plugins/<plugin name>/<test case> - single plugins
apps/<app name>/... - a collection of plugins
```
