### ISSUE TITLE
feat: improve table plugins

### ISSUE THREAD

**Issue by awesthouse** [equinor/dm-core-packages#258]
- [x] Map from objects to array instead of mapping from objects to objects with array values
- [x] Add option to open in new tab
- [x] Add config to allow user to select between open in new tab or inline
- [x] Add pagination (dm-core)
- [x] Fix markup error when in non-edit mode
- [x] Possibility to define open or expand, both, or neither, actions in configuration, plus their relevant views.
- [x] In the column headers, use "label" (or title?) when specified in blueprint. If not specified then use "name".
- [x] Add pagination button titles @roar-larsen #366
- [x] When you submit the form, two instances are stored. Same happens when you edit an item. https://github.com/equinor/data-modelling-storage-service/pull/512 @KristianKjerstad 
- [x] Fix bug with pagination: If you add enough items so that pagination becomes active, you can now paginate beyond the number of items in the table: 
![Image](https://github.com/equinor/dm-core-packages/assets/38418577/90c2ed9a-1fe3-4c20-8e75-a46a3a2ad363)
- [ ] when save, only update the rows that have changes

**Comment by KristianKjerstad** [comment]
add support for adding rows for       "contained": false

**Comment by roar-larsen** [comment]
Question: Should you be able to open the same table/list item more than once at the same time? Currently you can, there is no limitations on opening an item that's already open.


![Image](https://github.com/equinor/dm-core-packages/assets/38418577/999a40db-5616-4cc5-ac2e-71d8ec2b5c9f)
