### ISSUE TITLE
feat: add filtering logic (roles) to dm-core that can be used by ui plugin selector

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-core-packages#281]
The goal is to have different views for different roles. 

When a user log in to the web app, he is assigned a role. The role for users are defined in azure: https://portal.azure.com/?feature.msaljs=true#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/AppRoles/appId/97a6b5bd-63fb-42c6-bb75-7e5de2394ba0/isMSAApp~/false

you can assign a role to a user inside the enterprise application "Marine Analyis Framework Data Modelling Tool "  - https://portal.azure.com/#view/Microsoft_AAD_IAM/ManagedAppMenuBlade/~/Users/objectId/b9041025-05f0-44d4-89a7-3b5f955c0de5/appId/97a6b5bd-63fb-42c6-bb75-7e5de2394ba0

The roles concept has been implemented before in the analysis platform app. In this app, we added roles to the UI plugin like this: 

![Image](https://github.com/equinor/dm-core-packages/assets/69512295/954e64ac-c5d3-4e96-8385-0c7b3a255114)

the roles list defines all roles that should display a given plugin. So the inspector role should display the view-analysis-inspector plugin and other roles should display a different plugin

note: the userInfo component, used in the Header plugin, can be used to view your role.

![Image](https://github.com/equinor/dm-core-packages/assets/69512295/13bac711-a96a-47bb-9b4a-1d14c64f42de)

----------------------
```
{
  "type": "CORE:RecipeLink",
  "_blueprintPath_": "/plugins/grid/blueprints/Dashboard",
  "initialUiRecipe": {
    "name": "Dashboard",
    "type": "CORE:UiRecipe",
    "roles": ["Operator", "Admin"],
    "plugin": "@development-framework/dm-core-plugins/grid",
    "config": {
      "type": "PLUGINS:dm-core-plugins/grid/GridPluginConfig",
      "size": {
        "type": "PLUGINS:dm-core-plugins/grid/GridSize",
        "columns": 6,
        "rows": 5
      },
      "items": [
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "scope": "aNestedObjectWithCustomUI",
            "recipe": "aRecipeName"
          },
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "rowStart": 1,
            "columnStart": 1,
            "rowEnd": 3,
            "columnEnd": 6
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "viewConfig": {
            "type": "CORE:InlineRecipeViewConfig",
            "scope": "aNestedObjectWithCustomUI",
            "recipe": {
              "type": "CORE:UiRecipe",
              "plugin": "@development-framework/dm-core-plugins/form",
              "name": "form",
              "config": {
                "type": "PLUGINS:dm-core-plugins/form/FormInput",
                "attributes": [
                  {
                    "type": "PLUGINS:dm-core-plugins/form/fields/StringField",
                    "name": "bar",
                    "widget": "TextareaWidget"
                  }
                ]
              }
            }
          },
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "rowStart": 1,
            "columnStart": 4,
            "rowEnd": 3,
            "columnEnd": 6
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "scope": "orders[0].product",
            "recipe": "Yaml"
          },
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "rowStart": 5,
            "columnStart": 3,
            "rowEnd": 6,
            "columnEnd": 7
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "viewConfig": {
            "type": "CORE:ReferenceViewConfig",
            "scope": "order.product",
            "recipe": "Form"
          },
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "rowStart": 3,
            "columnStart": 3,
            "rowEnd": 6,
            "columnEnd": 5
          }
        },
        {
          "type": "PLUGINS:dm-core-plugins/grid/GridItem",
          "viewConfig": {
            "type": "CORE:InlineRecipeViewConfig",
            "recipe": {
              "type": "CORE:UiRecipe",
              "plugin": "@development-framework/dm-core-plugins/json",
              "name": "Json"
            }
          },
          "gridArea": {
            "type": "PLUGINS:dm-core-plugins/grid/GridArea",
            "rowStart": 3,
            "columnStart": 1,
            "rowEnd": 6,
            "columnEnd": 3
          }
        }
      ]
    }
  },
  "uiRecipes": [
    {
      "name": "Yaml",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/yaml"
    },
    {
      "name": "Edit",
      "type": "CORE:UiRecipe",
      "plugin": "@development-framework/dm-core-plugins/form"
    }
  ]
}

```

**Comment by KristianKjerstad** [comment]
task list

- [ ] define what roles we want to use in dm-core-packages and add them to the Marine Analyis Framework Data Modelling Tool app registration in azure. Suggestion for roles to start with: "admin" and "viewer".
- [ ] @eoaksnes needs to give every team member the "config owner" access to the enterprise application "Marine Analyis Framework Data Modelling Tool" (https://portal.azure.com/#view/Microsoft_AAD_IAM/ManagedAppMenuBlade/~/Owners/objectId/b9041025-05f0-44d4-89a7-3b5f955c0de5/appId/97a6b5bd-63fb-42c6-bb75-7e5de2394ba0) - so that all developers can change their own app role at will
- [ ] add roles list as an attribute in the UiRecipe blueprint in DMSS (an optional list of strings)
- [ ] add authentication to the example app. Right now, we don't have authentication, threfore no users have any roles.
- [ ] document roles concept in dm-docs
- [ ] add a way to make it simple for developer to change roles. 
- [ ] create an example in dm-core-packages that uses roles. Update the  



note: the userInfo component, used in the Header plugin, can be used to view your role.


![Image](https://github.com/equinor/dm-core-packages/assets/69512295/13bac711-a96a-47bb-9b4a-1d14c64f42de)

**Comment by KristianKjerstad** [comment]
todo define how to implement functionality that different ui recipes / different configs are used for differnet roles. see analysis platform for example

**Comment by KristianKjerstad** [comment]
todo should we support different config for different roles or only different plugin for different roles?

**Comment by eoaksnes** [comment]
If we implement this in the view selector, this will handle most of our use case. Need to create config.

**Comment by collinlokken** [comment]
We had a small discussion today if the filtering logic could be carried out on the backend instead, so that different roles will get different recipes from the API
