### ISSUE TITLE
bug: when clicking on "sub attributes" in the tree, objects are not resovled.

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#394]
example: click on the positive attribute inside employee1

![Image](https://github.com/equinor/dm-core-packages/assets/69512295/432e90e3-de67-48e3-a061-8f49f0432617)

This will return a link reference from dmss instead of the resolved document.

Should we always resolve the document in this case?

Should it behave the same for storage and link references?

**Comment by eoaksnes** [comment]
it works on
