### ISSUE TITLE
feat:  add refresh button to easy reload plugins

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#402]
Refreshable=true flag? 

small button that appears when you hover close to top right corner. 
refreshes

- 

Right now, it is cumbersome to reload plugins. To update the plugins, you have to refresh the entire page. Since we don't have any url routing implemented, this means that afer you refresh you have to navigate in the tree to where you want to go after refresh.

Could also be solved by adding url paths.

For example:
The url http://localhost:3000/demoDataSpurce/apps/MySignalApp/signalApp will open the signalApp entity 

![Image](https://github.com/equinor/dm-core-packages/assets/69512295/19ecd3cb-3e6b-431d-94eb-a1bee818e10d)

**Comment by eoaksnes** [comment]
Please update so that it is default off.
