### ISSUE TITLE
fix: File blueprint is wrong.

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#403]
ref discussion in https://github.com/equinor/dm-core-packages/pull/393

from some parts of dmss it looks like if type is "binary", it is interpreted as a storage reference.
![image](https://github.com/equinor/dm-core-packages/assets/69512295/f5629b44-32a2-476e-a752-208f012bd640)

However, from the implementation of the File plugin in dm-core-packages it looks like a link reference is required.
So I dont know if we should use link or storage reference for binary type.

we need to document how the binary attributetype is supposed to work

**Comment by KristianKjerstad** [comment]
see also #484

**Comment by eoaksnes** [comment]
The `content` inside the File blueprint should be of reference type storage.

**Comment by KristianKjerstad** [comment]
- binary type should NOT always be treated as blob storage type. We need to define this in the storage recipe.

**Comment by KristianKjerstad** [comment]
The blueprint File in dmss needs to be updated. remove the contained false.
