### ISSUE TITLE
feat(UI): Modify UI job runner plugin, by adding Start Arrow and Stop icons.

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#459]
For now the signal job ui is quite messy. Want to have it very _user_-friendly, not for a developer, but a user of the application

- [x] With start arrow > and stop button. 
    - [x]  Find nice EDS iconds for this. 
- [x] Have "run again" job after the job is finished. 
- [ ] Either manual-refresh button or continously ping every 2/5 seconds while the job is running.

**Comment by henrikbossart** [comment]
Am I correct in assuming that this signal app doesn't actually work atm? and that the data generated when running the simulation is just a hard coded random example? 🤔
