### ISSUE TITLE
feat(form): allow for extra input validation

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/dm-core-packages#467]
This was a bug earlier:
> If you in the blueprint state that a checkbox should be required to check (e.g. for confirmation purposes) before submitting, this does not work. You can now submit even though the box is left unchecked, this should not be possible. There should also be a text telling the user that the field must be check off before proceeding.

But really it is a feat. Should we make it possible to add extra input validation the parts of the form? Ie a checkbox that must be true, or a number that must be positive? Or should we require the use of widgets instead?

A string can easily be validated with a regex.
A number would need configs such as max, min, multipleOf, and a list of valid numbers.
A bool would be simply true/false

But what if they are intertwined? Ie a form where you first answer "Number of kids", and then have an array where you list their age. Then the "Number of kids" should match the length of the array. The example is not very realistic, but there are good examples where this might be an issue. How should we enable it?

**Comment by henrikbossart** [comment]
Having form validation per field makes total sense to me. Although forcing a checkbox to be true makes less sense ( at least in any usecases I can imagine for this project. Would make sense to require consent for something. I digress...).

I'm not 100% sure what you mean by widgets, but to me it makes sense specifying a form inputs requirements in the recipe(or is it blueprint?? 🤔).

I think for cases like the kids-case, it makes more sense to make custom fields where we can more tightly control the relations and validity between fields.
