### ISSUE TITLE
Refactor: Switch from CRA to VITE

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#480]
Migration Guide

https://dev.to/henriquejensen/migrating-from-create-react-app-to-vite-a-quick-and-easy-guide-5e72

**Comment by GIT-Gizmo** [comment]
Hi, you can assign this issue to me and I'll give it a go

**Comment by henrikbossart** [comment]
Should we swap node for bun at the same time? 😎

**Comment by eoaksnes** [comment]
duplicate
