### ISSUE TITLE
feat: The app should have a router for ease of use

### ISSUE THREAD

**Issue by henrikbossart** [equinor/dm-core-packages#533]
Not having routes for individual views in the apps is going to be a huge painpoint for end users.

**Comment by henrikbossart** [comment]
Kinda tricky, as we probably already knew... Its not that straight forward adding a router to an app that heavily relies on external packages to control which "pages" to show...

**Comment by eoaksnes** [comment]
`/ID_APP/ID_TREE/PATH/STUDY/CASES/0`
