### ISSUE TITLE
feat(explorer): make it possible to see the whole tree when expanding it

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-core-packages#569]
![Image](https://github.com/equinor/dm-core-packages/assets/1190419/11d7825b-a9aa-4947-a401-9ab437643f71)

How to solve?

- [ ] Should be possible to move the vertical line?
- [ ] Should be possible to have scrollbar on hortizontal for the tree?

**Comment by henrikbossart** [comment]
From the picture this looks to be happening in the 'Signal App', when viewing the explorer, correct?
I'm not able to reproduce this issue, as I get a horizontal scrollbar when the tree overflows its container. 

Can you provide steps to reproduce?
