### ISSUE TITLE
fix(grid): columnEnd is off by one

### ISSUE THREAD

**Issue by soofstad** [equinor/dm-core-packages#638]
#### Expected Behaviour

Given a grid 2x2; I expect to define a view to end in the last column to have `"columnEnd": 2`.

#### Actual Behaviour
"columnEnd" needs to be set to "3" for the view to take the whole width.

**Comment by henrikbossart** [comment]
Maybe I'm not fully understanding your issue, but when I create 2x2 grid, my items span the full width when I have one element in each grid-cell.

**Comment by soofstad** [comment]
Say you want one view to span the whole first row.
What do you have to set as "columnEnd" then? I found it to be 3, when it should be 2.

**Comment by henrikbossart** [comment]
huh, you're right... weird..

**Comment by henrikbossart** [comment]
aaah, this happens because the `grid-column-end` property references the _grid line_ and not the column
