### ISSUE TITLE
Add TailwindCSS

### ISSUE THREAD

**Issue by henrikbossart** [equinor/dm-core-packages#699]
IMO this greatly improves readability and maintainability of styling. There is a learning curve, but once one gets the hang of it, its amazing.

**Comment by pbullhove** [comment]
Tailwind is very nice, I approve.

**Comment by henrikbossart** [comment]
I agree, I'm very fond of it

**Comment by pbullhove** [comment]
Though I guess there is not too much manual styling that we are doing?
Most of the styling is embedded in the EDS components, right?

**Comment by henrikbossart** [comment]
I guess :(
