### ISSUE TITLE
feat: example of how to validate inputs to plugins

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#73]

**Comment by eoaksnes** [comment]
For the validation endpoint the input should be:
 - validation type (optional) 
 - entity
 - mode (minimum, restrict/complete)

Note that the minimum mode will be used by plugins.

**Comment by eoaksnes** [comment]
For the input validation inside UI plugins.

- The validation should be optional.
- Add blueprintPath to plugins.js that will be provided to the plugins, so that it knows where the blueprints are stored.

**Comment by eoaksnes** [comment]
Both the document and plugin config that comes into the plugin should be validated.

**Comment by eoaksnes** [comment]
Use the "plugin storage directory" to get the blueprints for validation.

**Comment by soofstad** [comment]
This is started in https://github.com/equinor/dm-core-packages/pull/92.
Should update this to assume bluerpints are in "dmss://system/Plugins". Would then no longer need to add this extra blueprint path thing to "UiPluginContext".
