### ISSUE TITLE
fix: when updating name of a newly created blueprint in the explorer plugin, the name is not updated in the tree view

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#75]
the name "newname" should be displayed in the tree view instead of WorkflowDS/fc98.....

![Image](https://user-images.githubusercontent.com/69512295/216963397-ab0f1267-1de1-43ec-a2f0-a30cd29fbdb8.png)

**Comment by KristianKjerstad** [comment]
Renaming is not supported in DMSS.

**Comment by KristianKjerstad** [comment]
this is an issue with the content list of a package. When an entity contained in a package is updated, the content list is not updated....

**Comment by soofstad** [comment]
closed by #82
