### ISSUE TITLE
fix(jobplugin): improve feedback from jobplugin

### ISSUE THREAD

**Issue by collinlokken** [equinor/dm-core-packages#753]
- [x] Show status of job at all times
- [x] Format the logs (not one single line)
- [x] hide buttons in recipe
- [x] show all logs in widget
- [x] progress bar
- [x] possibility to post status, progress and log to job-api from the job
- [x] round green button to start, when running color should change to red to stop
- [x] pop up confirmation on stop job
- [x] remove/stop jobs

**Comment by collinlokken** [comment]
Possible solution:


![Image](https://github.com/equinor/dm-core-packages/assets/43639886/addc942c-74da-4da1-b62d-073c8f287b29)

**Comment by pbullhove** [comment]
EDS icon play_circle, and stop_circle can be used
