### ISSUE TITLE
feat(table): use tableplugin to show/edit blueprint attributes

### ISSUE THREAD

**Issue by collinlokken** [equinor/dm-core-packages#755]

**Comment by pbullhove** [comment]
Right now we have a custom list for attributes. 
Kinda wondering what we would gain by changing from what we have now? 

It's ugly so it could need some UX love though. 

![Image](https://github.com/equinor/dm-core-packages/assets/37016135/99666b13-1e6d-4113-8c9a-39018743dbb7)

**Comment by pbullhove** [comment]
Use listplugin + tableplugin. 
Also make the view comparable to the rest of the plugins.
