### ISSUE TITLE
feat: plugins should have a README with a minimum blueprint for compatible types

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#78]
- [ ] Write the main README.md file
 - [ ] Write README.md file for each plugin
 - [ ] Autogenerate documentation based on docstring

**Comment by KristianKjerstad** [comment]
see example here: https://github.com/equinor/dm-core-packages/blob/f45e8d6b665daf69f711ee73df6267b677133167/packages/dm-core-plugins/README.md

**Comment by eoaksnes** [comment]
One single main README.md file in the root of dm-core-plugins, which contains overview of all plugins.

Every plugin should have also README.md that explains that the plugin does and example of how to use.

**Comment by eoaksnes** [comment]
Autogenerate to dm-docs: config parameters.
