### ISSUE TITLE
fix: hide binary in tree

### ISSUE THREAD

**Issue by eoaksnes** [equinor/dm-core-packages#790]
![Image](https://github.com/equinor/dm-core-packages/assets/1190419/c8966719-f36c-4def-8d75-354847818537)

**Comment by roar-larsen** [comment]
@soofstad When there are no visible items, can the chevron be removed? It now indicates that the item is expandable when in reality there is nothing to expand.

![Image](https://github.com/equinor/dm-core-packages/assets/38418577/5eb97367-1553-4775-ae46-08a137658c06)

**Comment by soofstad** [comment]
The original fix included that @roar-larsen, as can be seen in the screenshot in that PR.
Was this not added back in the "second round" @henrikbossart ?

**Comment by henrikbossart** [comment]
I thought I fixed that? 🤔 

![Screenshot 2023-12-07 at 12 15 40](https://github.com/equinor/dm-core-packages/assets/3105885/e0abb3aa-80d1-443b-aa00-754c69608194)

**Comment by henrikbossart** [comment]
oops

**Comment by henrikbossart** [comment]
https://github.com/equinor/dm-core-packages/pull/923
