### ISSUE TITLE
Bug: State handling is unstabile

### ISSUE THREAD

**Issue by roar-larsen** [equinor/dm-core-packages#852]
There seem to be an issue with the state handling which causes the model uncontained test to fail. The issue is only observed in the CI, locally it works fine.

Trace view from test: https://equinor.github.io/dm-core-packages/reports/fix/uncommenting-model-uncontained-test/7057585418/1/#?testId=e08ba43ef8ef52ba1956-dccefeb2aa9fff0b1d7c

**Comment by eoaksnes** [comment]
@roar-larsen is still valid?

**Comment by roar-larsen** [comment]
@eoaksnes I think so, but I can check. The part that was failing in the test has been commented out.

**Comment by roar-larsen** [comment]
@eoaksnes Issue still seems to be there, the test is failing about 50% of the time. And I don´t think there is anything wrong with the test itself.

**Comment by roar-larsen** [comment]
Updated test to wait on API-request which seem to work. Decided not to investigate issue further.
