### ISSUE TITLE
fix(dm-cli):_ Reset app does not clean up everything.

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#858]
Gets a duplicate entity issue on running ./reset-app.sh

Steps to reproduce: 
- Start changing entities and run the ./reset-app.sh. again 
- Sometimes you get the error. 

![Image](https://github.com/equinor/dm-core-packages/assets/37016135/722ae556-5660-4ba8-994d-bb562e960495)

**Comment by collinlokken** [comment]
Maybe change the repository to dm-cli?
