### ISSUE TITLE
feat(table): The name of newly created list/table entities should be default name of attribute + index

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#859]
Steps to Reproduce: 
- go to proxy. app and fetch table, create a new row, and open it. It will now have the name "date". 

Expected behavior. 
- Want the name of the tab to be the name of the attribute + index. (counter) 
-

**Comment by collinlokken** [comment]
This is not a bug. The blueprint for Task (job) extends from `/mtsmo/basic/NamedEntity` in which "date" is the default value for name. This is correct behaviour in other words
