### ISSUE TITLE
fix(table-stuff): Bugs

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#861]
- [x] Submitting of form/uiRecipe inside table does not work? 

https://equinor.slack.com/files/UKFDMCY8M/F067ZDZALFR/table-inner-ui.gif

![Image](https://github.com/equinor/dm-core-packages/assets/37016135/c99daf4b-7116-455a-a3cb-3128836f6f15)

- [x] Icon add not Found on table. Use data instead for all icons. 

- [ ] Deleting, reordering does not update the index, so uiPlugin looks for indexes at the wrong places.

**Comment by awesthouse** [comment]
Could not reproduce both remaining issues, but changes have been made that could affect these bugs so let's test again in simpos app before doing any more work
