### ISSUE TITLE
Table/List:  Default entity on create - create new entities with different values

### ISSUE THREAD

**Issue by pbullhove** [equinor/dm-core-packages#957]
So if you have 20 different platforms. 

PlatformBlueprint
entity: AGSB, 
simualtion
- defaultValues

where can we set the defaultvalues for simulations in ASGB, that are different from ASGB2? 
Don't want to make 20 different blueprints for every different platform, should be able to set

## Solution 
Start doing this with table, this solves 80% of the problems. 

In the TableConfig, be able to specify template for newly created entity. 
- 

In the UIRecipe
- add a relative path to the document that holds the defaultvalues.

**Comment by eoaksnes** [comment]
Most important is table.

**Comment by eoaksnes** [comment]
Be able to create new items and specify template:

```json
"config": {
  "type": "PLUGINS:dm-core-plugins/table/TablePluginConfig",
  "templates": [
      {
        "type": "Refernce",
        "referenceType": "link",
        "address": "...."
      }
  ],
```
