### ISSUE TITLE
refactor: find good structure and naming for plugins in dm-core-plugins

### ISSUE THREAD

**Issue by KristianKjerstad** [equinor/dm-core-packages#96]
blocked by PR https://github.com/equinor/dm-core-packages/pull/95

We should have a common structure for import of plugins (like blueprint, yaml-view, ++)

now, the component naming for exported plugins is inconsistent:
```
  {
    pluginName: 'explorer',
    component: Editor,
  },
  {
    pluginName: 'yaml-view',
    component: PluginComponent,
  },
  {
    pluginName: 'tabs',
    component: TabsContainer,
  },
```

**Comment by eoaksnes** [comment]
{
  pluginName: <name>,
  component: <name>Plugin
}

Rename 

* default-preview to json
* default-pdf to pdf
* yaml-view to yaml
* edit-blueprint to blueprint
* mermaid to blueprint-hierarchy

**Comment by eoaksnes** [comment]
Prefix plugin names with npm package name: @development-framework/dm-core-plugins/<plugin>

**Comment by KristianKjerstad** [comment]
https://github.com/equinor/dm-core-packages/issues/116
